### ISSUE TITLE
Fix Canvas

### ISSUE THREAD

**Issue by rebeccahom** [nyu-software-engineering/drawing-with-friends#83]
Canvas broke after latest update

**Comment by jeph** [comment]
The canvas broke because the paths to the assets the canvas required were changed leading to a 404 error in console. This explains the persistent `Loading...` state. Since file-loader is set up now, we can simply keep the assets in our repo and have them in our bundle.  😄 

It might also be best to make a folder to keep the image assets in and move all the assets into the repo.
